version: '2'
services:
  erdbizapplication-app:
    image: erdbizapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://erdbizapplication-mysql:3306/erdbizapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  erdbizapplication-mysql:
    extends:
      file: mysql.yml
      service: erdbizapplication-mysql
